"ues client";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { Providers } from "./components/Provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="w-full h-full">
			<body className={`${inter.className}  p-0 w-full h-full`}>
				<ThemeProvider attribute="class" enableSystem>
					<Providers>
						<main className="w-full h-full flex flex-row items-start justify-start overflow-x-hidden overflow-y-auto">
							{children}
						</main>
					</Providers>
				</ThemeProvider>
			</body>
		</html>
	);
}
