import { ReduxProvider } from "@/redux/Provider";
import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="w-full h-full">
			<body
				className={`${inter.className} dark text-foreground bg-background  w-full h-full  p-0`}
			>
				<ReduxProvider>
					<NextUIProvider className="w-full h-full p-0">
						{children}
					</NextUIProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
